spring:
  application:
    name: eureka-server

---
spring:
  profiles: eureka-server1
server:
  port: 8001
eureka:
  instance:
    hostname: 192.168.150.130
    prefer-ip-address: true
    instance-id: 192.168.150.130:8001
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.150.130:8002/eureka/

---
spring:
  profiles: eureka-server2
server:
  port: 8002
eureka:
  instance:
    hostname: 192.168.150.130
    prefer-ip-address: true
    instance-id: 192.168.150.130:8002
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.150.130:8001/eureka/
